# type: ignore

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PublicIncreaseDepthsV3Api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PublicIncreaseDepthsV3Api.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\034com.mxc.push.common.protobufB\036PublicIncreaseDepthsV3ApiProtoH\001P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fPublicIncreaseDepthsV3Api.proto\"\x99\x01\n\x19PublicIncreaseDepthsV3Api\x12+\n\x04\x61sks\x18\x01 \x03(\x0b\x32\x1d.PublicIncreaseDepthV3ApiItem\x12+\n\x04\x62ids\x18\x02 \x03(\x0b\x32\x1d.PublicIncreaseDepthV3ApiItem\x12\x11\n\teventType\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\"?\n\x1cPublicIncreaseDepthV3ApiItem\x12\r\n\x05price\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\tBB\n\x1c\x63om.mxc.push.common.protobufB\x1ePublicIncreaseDepthsV3ApiProtoH\x01P\x01\x62\x06proto3'
)




_PUBLICINCREASEDEPTHSV3API = _descriptor.Descriptor(
  name='PublicIncreaseDepthsV3Api',
  full_name='PublicIncreaseDepthsV3Api',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='asks', full_name='PublicIncreaseDepthsV3Api.asks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bids', full_name='PublicIncreaseDepthsV3Api.bids', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventType', full_name='PublicIncreaseDepthsV3Api.eventType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='PublicIncreaseDepthsV3Api.version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=189,
)


_PUBLICINCREASEDEPTHV3APIITEM = _descriptor.Descriptor(
  name='PublicIncreaseDepthV3ApiItem',
  full_name='PublicIncreaseDepthV3ApiItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='PublicIncreaseDepthV3ApiItem.price', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='PublicIncreaseDepthV3ApiItem.quantity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=254,
)

_PUBLICINCREASEDEPTHSV3API.fields_by_name['asks'].message_type = _PUBLICINCREASEDEPTHV3APIITEM
_PUBLICINCREASEDEPTHSV3API.fields_by_name['bids'].message_type = _PUBLICINCREASEDEPTHV3APIITEM
DESCRIPTOR.message_types_by_name['PublicIncreaseDepthsV3Api'] = _PUBLICINCREASEDEPTHSV3API
DESCRIPTOR.message_types_by_name['PublicIncreaseDepthV3ApiItem'] = _PUBLICINCREASEDEPTHV3APIITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PublicIncreaseDepthsV3Api = _reflection.GeneratedProtocolMessageType('PublicIncreaseDepthsV3Api', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICINCREASEDEPTHSV3API,
  '__module__' : 'PublicIncreaseDepthsV3Api_pb2'
  # @@protoc_insertion_point(class_scope:PublicIncreaseDepthsV3Api)
  })
_sym_db.RegisterMessage(PublicIncreaseDepthsV3Api)

PublicIncreaseDepthV3ApiItem = _reflection.GeneratedProtocolMessageType('PublicIncreaseDepthV3ApiItem', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICINCREASEDEPTHV3APIITEM,
  '__module__' : 'PublicIncreaseDepthsV3Api_pb2'
  # @@protoc_insertion_point(class_scope:PublicIncreaseDepthV3ApiItem)
  })
_sym_db.RegisterMessage(PublicIncreaseDepthV3ApiItem)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
