# type: ignore

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PublicIncreaseDepthsBatchV3Api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import PublicIncreaseDepthsV3Api_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PublicIncreaseDepthsBatchV3Api.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\034com.mxc.push.common.protobufB#PublicIncreaseDepthsBatchV3ApiProtoH\001P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$PublicIncreaseDepthsBatchV3Api.proto\x1a\x1fPublicIncreaseDepthsV3Api.proto\"^\n\x1ePublicIncreaseDepthsBatchV3Api\x12)\n\x05items\x18\x01 \x03(\x0b\x32\x1a.PublicIncreaseDepthsV3Api\x12\x11\n\teventType\x18\x02 \x01(\tBG\n\x1c\x63om.mxc.push.common.protobufB#PublicIncreaseDepthsBatchV3ApiProtoH\x01P\x01\x62\x06proto3'
  ,
  dependencies=[PublicIncreaseDepthsV3Api_pb2.DESCRIPTOR,])




_PUBLICINCREASEDEPTHSBATCHV3API = _descriptor.Descriptor(
  name='PublicIncreaseDepthsBatchV3Api',
  full_name='PublicIncreaseDepthsBatchV3Api',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='PublicIncreaseDepthsBatchV3Api.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventType', full_name='PublicIncreaseDepthsBatchV3Api.eventType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=167,
)

_PUBLICINCREASEDEPTHSBATCHV3API.fields_by_name['items'].message_type = PublicIncreaseDepthsV3Api_pb2._PUBLICINCREASEDEPTHSV3API
DESCRIPTOR.message_types_by_name['PublicIncreaseDepthsBatchV3Api'] = _PUBLICINCREASEDEPTHSBATCHV3API
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PublicIncreaseDepthsBatchV3Api = _reflection.GeneratedProtocolMessageType('PublicIncreaseDepthsBatchV3Api', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICINCREASEDEPTHSBATCHV3API,
  '__module__' : 'PublicIncreaseDepthsBatchV3Api_pb2'
  # @@protoc_insertion_point(class_scope:PublicIncreaseDepthsBatchV3Api)
  })
_sym_db.RegisterMessage(PublicIncreaseDepthsBatchV3Api)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
