import trading_sdk as tdk

class Trading(tdk.Trading):
  ...
  # async def place_order(self, symbol: str, order: tdk.Trading.Order):
  #   ...

  # async def cancel_order(self, symbol: str, *, order_id: str):
  #   ...

  # async def cancel_all_orders(self, symbol: str):
  #   ...

  # async def query_order(self, symbol: str, *, order_id: str):
  #   ...

  # async def get_balances(self, *currencies: str):
  #   ...