[project]
site_name = "Typed MEXC"
site_description = "Fully typed, validated async client for the MEXC APIs."
repo_name = "mexc"
repo_url = "https://github.com/tribulnation/mexc"
copyright = """
Copyright &copy; 2026 Tribulnation
"""
nav = [
  { "Intro" = "index.md" },
  { "Getting Started" = "getting-started.md" },
  { "API Keys Setup" = "api-keys.md" },
  { "API Overview" = "api-overview.md" },
  { "How To" = [
    { "Overview" = "how-to/index.md" },
    "how-to/fetch-market-data.md",
    "how-to/place-and-manage-spot-orders.md",
    "how-to/fetch-balances-positions-and-history.md",
    "how-to/listen-to-streams.md",
  ] },
  { "Reference" = [
    { "Overview" = "reference/index.md" },
    "reference/async-usage.md",
    "reference/error-handling.md",
    "reference/env-vars.md",
    { "API" = [
      { "Overview" = "reference/api/index.md" },
      "reference/api/mexc.md",
      "reference/api/spot.md",
      "reference/api/futures.md",
    ] },
  ] },
]

[project.theme]
language = "en"
logo = "media/logo.png"
favicon = "media/logo.png"
features = [
  "content.code.copy",
]

[[project.theme.palette]]
scheme = "slate"
primary = "black"
accent = "amber"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
scheme = "default"
primary = "black"
accent = "amber"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.extra]
homepage = "https://tribulnation.com"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true

[project.markdown_extensions.pymdownx.superfences]

[project.plugins.mkdocstrings.handlers.python]
paths = ["pkg/src"]
inventories = ["https://docs.python.org/3/objects.inv"]
