from datetime import datetime
from typing_extensions import AsyncIterator, TypedDict
from mexc.spot.core import AuthSpotMixin, ErrorResponse
from mexc.core import Timestamp, timestamp as ts, validator

class DetailItem(TypedDict):
  """Rebate record."""
  asset: str
  """Rebate asset."""
  type: str
  """Rebate source type, such as spot or futures."""
  rate: str
  """Rebate rate."""
  amount: str
  """Rebate amount."""
  uid: str
  """Invitee user id."""
  account: str
  """Masked invitee account."""
  tradeTime: datetime
  """Trade time in milliseconds."""
  updateTime: datetime
  """Record update time in milliseconds."""

class DetailResponse(TypedDict):
  """Paginated rebate response."""
  page: int
  """Current result page."""
  totalRecords: int
  """Total number of matching records."""
  totalPageNum: int
  """Total number of result pages."""
  data: list[DetailItem]
  """Result records for the page."""

Response: type[DetailResponse | ErrorResponse] = DetailResponse | ErrorResponse # type: ignore
adapter = validator(Response)

class Detail(AuthSpotMixin):
  async def detail(
    self,
    *,
    start_time: Timestamp | None = None,
    end_time: Timestamp | None = None,
    page: int | None = None,
    recv_window: int | None = None,
    timestamp: Timestamp | None = None,
    validate: bool | None = None
  ) -> DetailResponse:
    """Returns rebate records generated by invited users and their sub-accounts across spot and futures transactions.

    Args:
      start_time: Start time in milliseconds.
      end_time: End time in milliseconds.
      page: Result page; defaults to 1.
      recv_window: Optional receive window in milliseconds.
      timestamp: Signed request timestamp in milliseconds.
      validate: Validation override for this request.

    Returns:
      The validated endpoint response.

    References:
      - [MEXC API docs](https://mexcdevelop.github.io/apidocs/spot_v3_en/#get-rebate-records-detail)
    """
    if timestamp is None:
      timestamp = ts.now()
    params = {}
    if start_time is not None:
      params['startTime'] = ts.dump_ms(start_time)
    if end_time is not None:
      params['endTime'] = ts.dump_ms(end_time)
    if page is not None:
      params['page'] = page
    if recv_window is not None:
      params['recvWindow'] = recv_window
    if timestamp is not None:
      params['timestamp'] = ts.dump_ms(timestamp)
    r = await self.signed_request('GET', '/api/v3/rebate/detail', params=params)
    return self.output(r.text, adapter, validate)

  async def detail_paged(self, *, start_time: Timestamp | None = None, end_time: Timestamp | None = None, recv_window: int | None = None, timestamp: Timestamp | None = None, max_pages: int | None = None, validate: bool | None = None) -> AsyncIterator[DetailResponse]:
    """Yield pages from `detail` until the response reports the final page."""
    page = 1
    while True:
      response = await self.detail(start_time=start_time, end_time=end_time, recv_window=recv_window, timestamp=timestamp, page=page, validate=validate)
      yield response
      if max_pages is not None and page >= max_pages:
        break
      data = response.get('data') if isinstance(response, dict) else None
      total = None
      if isinstance(data, dict):
        total = data.get('totalPage') or data.get('totalPageNum')
      if total is None and isinstance(response, dict):
        total = response.get('totalPage') or response.get('totalPageNum')
      if total is None:
        if data == [] or response == []:
          break
        if max_pages is None:
          break
        page += 1
        continue
      if total is None or page >= total:
        break
      page += 1
