# type: ignore

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PublicLimitDepthsV3Api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PublicLimitDepthsV3Api.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\034com.mxc.push.common.protobufB\033PublicLimitDepthsV3ApiProtoH\001P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cPublicLimitDepthsV3Api.proto\"\x90\x01\n\x16PublicLimitDepthsV3Api\x12(\n\x04\x61sks\x18\x01 \x03(\x0b\x32\x1a.PublicLimitDepthV3ApiItem\x12(\n\x04\x62ids\x18\x02 \x03(\x0b\x32\x1a.PublicLimitDepthV3ApiItem\x12\x11\n\teventType\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\"<\n\x19PublicLimitDepthV3ApiItem\x12\r\n\x05price\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\tB?\n\x1c\x63om.mxc.push.common.protobufB\x1bPublicLimitDepthsV3ApiProtoH\x01P\x01\x62\x06proto3'
)




_PUBLICLIMITDEPTHSV3API = _descriptor.Descriptor(
  name='PublicLimitDepthsV3Api',
  full_name='PublicLimitDepthsV3Api',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='asks', full_name='PublicLimitDepthsV3Api.asks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bids', full_name='PublicLimitDepthsV3Api.bids', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventType', full_name='PublicLimitDepthsV3Api.eventType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='PublicLimitDepthsV3Api.version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=177,
)


_PUBLICLIMITDEPTHV3APIITEM = _descriptor.Descriptor(
  name='PublicLimitDepthV3ApiItem',
  full_name='PublicLimitDepthV3ApiItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='PublicLimitDepthV3ApiItem.price', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='PublicLimitDepthV3ApiItem.quantity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=239,
)

_PUBLICLIMITDEPTHSV3API.fields_by_name['asks'].message_type = _PUBLICLIMITDEPTHV3APIITEM
_PUBLICLIMITDEPTHSV3API.fields_by_name['bids'].message_type = _PUBLICLIMITDEPTHV3APIITEM
DESCRIPTOR.message_types_by_name['PublicLimitDepthsV3Api'] = _PUBLICLIMITDEPTHSV3API
DESCRIPTOR.message_types_by_name['PublicLimitDepthV3ApiItem'] = _PUBLICLIMITDEPTHV3APIITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PublicLimitDepthsV3Api = _reflection.GeneratedProtocolMessageType('PublicLimitDepthsV3Api', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICLIMITDEPTHSV3API,
  '__module__' : 'PublicLimitDepthsV3Api_pb2'
  # @@protoc_insertion_point(class_scope:PublicLimitDepthsV3Api)
  })
_sym_db.RegisterMessage(PublicLimitDepthsV3Api)

PublicLimitDepthV3ApiItem = _reflection.GeneratedProtocolMessageType('PublicLimitDepthV3ApiItem', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICLIMITDEPTHV3APIITEM,
  '__module__' : 'PublicLimitDepthsV3Api_pb2'
  # @@protoc_insertion_point(class_scope:PublicLimitDepthV3ApiItem)
  })
_sym_db.RegisterMessage(PublicLimitDepthV3ApiItem)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
