# type: ignore

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PublicAggreDepthsV3Api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PublicAggreDepthsV3Api.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\034com.mxc.push.common.protobufB\033PublicAggreDepthsV3ApiProtoH\001P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cPublicAggreDepthsV3Api.proto\"\xa7\x01\n\x16PublicAggreDepthsV3Api\x12(\n\x04\x61sks\x18\x01 \x03(\x0b\x32\x1a.PublicAggreDepthV3ApiItem\x12(\n\x04\x62ids\x18\x02 \x03(\x0b\x32\x1a.PublicAggreDepthV3ApiItem\x12\x11\n\teventType\x18\x03 \x01(\t\x12\x13\n\x0b\x66romVersion\x18\x04 \x01(\t\x12\x11\n\ttoVersion\x18\x05 \x01(\t\"<\n\x19PublicAggreDepthV3ApiItem\x12\r\n\x05price\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\tB?\n\x1c\x63om.mxc.push.common.protobufB\x1bPublicAggreDepthsV3ApiProtoH\x01P\x01\x62\x06proto3'
)




_PUBLICAGGREDEPTHSV3API = _descriptor.Descriptor(
  name='PublicAggreDepthsV3Api',
  full_name='PublicAggreDepthsV3Api',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='asks', full_name='PublicAggreDepthsV3Api.asks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bids', full_name='PublicAggreDepthsV3Api.bids', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventType', full_name='PublicAggreDepthsV3Api.eventType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fromVersion', full_name='PublicAggreDepthsV3Api.fromVersion', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='toVersion', full_name='PublicAggreDepthsV3Api.toVersion', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=200,
)


_PUBLICAGGREDEPTHV3APIITEM = _descriptor.Descriptor(
  name='PublicAggreDepthV3ApiItem',
  full_name='PublicAggreDepthV3ApiItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='PublicAggreDepthV3ApiItem.price', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='PublicAggreDepthV3ApiItem.quantity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=262,
)

_PUBLICAGGREDEPTHSV3API.fields_by_name['asks'].message_type = _PUBLICAGGREDEPTHV3APIITEM
_PUBLICAGGREDEPTHSV3API.fields_by_name['bids'].message_type = _PUBLICAGGREDEPTHV3APIITEM
DESCRIPTOR.message_types_by_name['PublicAggreDepthsV3Api'] = _PUBLICAGGREDEPTHSV3API
DESCRIPTOR.message_types_by_name['PublicAggreDepthV3ApiItem'] = _PUBLICAGGREDEPTHV3APIITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PublicAggreDepthsV3Api = _reflection.GeneratedProtocolMessageType('PublicAggreDepthsV3Api', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICAGGREDEPTHSV3API,
  '__module__' : 'PublicAggreDepthsV3Api_pb2'
  # @@protoc_insertion_point(class_scope:PublicAggreDepthsV3Api)
  })
_sym_db.RegisterMessage(PublicAggreDepthsV3Api)

PublicAggreDepthV3ApiItem = _reflection.GeneratedProtocolMessageType('PublicAggreDepthV3ApiItem', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICAGGREDEPTHV3APIITEM,
  '__module__' : 'PublicAggreDepthsV3Api_pb2'
  # @@protoc_insertion_point(class_scope:PublicAggreDepthV3ApiItem)
  })
_sym_db.RegisterMessage(PublicAggreDepthV3ApiItem)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
