# type: ignore

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PublicBookTickerBatchV3Api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import PublicBookTickerV3Api_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PublicBookTickerBatchV3Api.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\034com.mxc.push.common.protobufB\037PublicBookTickerBatchV3ApiProtoH\001P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n PublicBookTickerBatchV3Api.proto\x1a\x1bPublicBookTickerV3Api.proto\"C\n\x1aPublicBookTickerBatchV3Api\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.PublicBookTickerV3ApiBC\n\x1c\x63om.mxc.push.common.protobufB\x1fPublicBookTickerBatchV3ApiProtoH\x01P\x01\x62\x06proto3'
  ,
  dependencies=[PublicBookTickerV3Api_pb2.DESCRIPTOR,])




_PUBLICBOOKTICKERBATCHV3API = _descriptor.Descriptor(
  name='PublicBookTickerBatchV3Api',
  full_name='PublicBookTickerBatchV3Api',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='PublicBookTickerBatchV3Api.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=132,
)

_PUBLICBOOKTICKERBATCHV3API.fields_by_name['items'].message_type = PublicBookTickerV3Api_pb2._PUBLICBOOKTICKERV3API
DESCRIPTOR.message_types_by_name['PublicBookTickerBatchV3Api'] = _PUBLICBOOKTICKERBATCHV3API
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PublicBookTickerBatchV3Api = _reflection.GeneratedProtocolMessageType('PublicBookTickerBatchV3Api', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICBOOKTICKERBATCHV3API,
  '__module__' : 'PublicBookTickerBatchV3Api_pb2'
  # @@protoc_insertion_point(class_scope:PublicBookTickerBatchV3Api)
  })
_sym_db.RegisterMessage(PublicBookTickerBatchV3Api)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
