PYTHON := "../.venv/bin/python"

help:
  @just --list

# Run type checking
check:
  pyright .

# Build the package (into `dist/`)
build:
  (rm -drf dist || :) && \
  pyright . && \
  cp ../README.md . && \
  cp ../LICENSE . && \
  {{PYTHON}} -m build && \
  rm README.md && \
  rm LICENSE && \
  rm -drf build

# Publish `dist/*` to pypi, then delete
publish: build
  {{PYTHON}} -m twine upload dist/* && \
  rm -drf dist

# Increase patch version
patch:
  $CIT_SCRIPTS/bump.sh pyproject.toml

# Increase patch version and publish
republish: patch publish
